# Name of the GitHub Actions Workflow
name: CI/CD - Deploy Static Website

# Defines when the workflow should run
on:
  # Run the workflow whenever code is pushed
  push:
    # Run the workflow only when the push happens to main branch
    branches:
      - main
  # Allows us to manually run the workflow using GitHub Actions UI
  workflow_dispatch:

# Defines permissions given to github actions
permissions: 
  # Allows the workflow to read repository contents
  contents: read
  # Allows the workflow to deploy to github pages
  pages: write
  # Allows the workflow to use OpenID Connect for authentication with github pages
  id-token: write

# Defines the jobs thet will be executed bt the workflow
jobs:
  # Job 1: Build
  build:
    name: Build
    runs-on: ubuntu-latest
    # Defines the steps that will be executed inside the build job
    steps:
      # Step 1
      # Checkout the repository code into the GitHub Actions runner
      - name: Checkout code
        # Uses GitHub checkout action
        uses: actions/checkout@v4

      # Step 2
      # Configures the GitHub Pages environment
      - name: Setup Pages
        # Uses confgiure-pages action
        uses: actions/configure-pages@v5

      # Step 3
      # Packages the website files into an artifact that can be deployed later to GitHub Pages
      - name: Upload website files
      # Uploading files as a Pages artifact
        uses: actions/upload-pages-artifact@v3
        # Configuration for the action
        with:
          # "." Means the current directory, all the website files in repository
          # will be included in the artifact
          path: .
  
  # Job 2: Deploy
  deploy:
    name: Deploy to GitHub Pages
    # This job will run only after the build job completed
    needs: build
    runs-on: ubuntu-latest
    # Defines the GitHub environment used
    environment:
      # Name of the environment
      name: github-pages
      # The url generated by deployment
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    # Step 1
    # Deploys the pages artifact to GitHub Pages
      - name: Deploy to GitHub Pages
        # Give this step an ID called "deployment".
        # This ID is used above: steps.deployment.outputs.page_url to get the URL of the deployed website.
        id: deployment
        # Uses GitHub Pages deployment actions
        uses: actions/deploy-pages@v4